totalseg_mapping = {1: 27, #'adrenal_gland_left',
                        2: 28, #'adrenal_gland_right',
                        3: 114,#'aorta',
                        4: 40, #'autochthon_left',
                        5: 41, #'autochthon_right', 
                        6: 25, #'brain', 
                        7: 93, #'clavicula_left',
                        8: 94, #'clavicula_right',
                        9: 10, # 'colon', 
                        10: 9, #'duodenum', 
                        11: 6, #'esophagus',
                        12: None, #'face', 
                        13: 103, #'femur_left',
                        14: 104, #'femur_right',
                        15: 12, #'gallbladder',
                        16: 32,#'gluteus_maximus_left',
                        17: 33, #'gluteus_maximus_right', 
                        18: 34,#'gluteus_medius_left',
                        19: 35,#'gluteus_medius_right',
                        20: 36,#'gluteus_minimus_left',
                        21: 37,#'gluteus_minimus_right', 
                        22: 106,#'heart_atrium_left',
                        23: 108,#'heart_atrium_right', 
                        24: 109,#'heart_myocardium', 
                        25: 110,#'heart_ventricle_left', 
                        26: 111,#'heart_ventricle_right',
                        27: 100,#'hip_left', 
                        28: 101,#'hip_right', 
                        29: 97,#'humerus_left', 
                        30: 98,#'humerus_right', 
                        31: 112,#'iliac_artery_left', 
                        32: 113,#'iliac_artery_right',
                        33: 115,#'iliac_vena_left', 
                        34: 116,#'iliac_vena_right', 
                        35: 38,#'iliopsoas_left',
                        36: 39,#'iliopsoas_right', 
                        37: 117,#'inferior_vena_cava',
                        38: 15,#'kidney_left', 
                        39: 16,#'kidney_right', 
                        40:13 ,#'liver',
                        41: 120,#'lung_lower_lobe_left', 
                        42: 122,#'lung_lower_lobe_right', 
                        43: 123,#'lung_middle_lobe_right', 
                        44: 121,#'lung_upper_lobe_left',
                        45: 124,#'lung_upper_lobe_right',
                        46: 14,#'pancreas', 
                        47: 118,#'portal_vein_and_splenic_vein', 
                        48: 127,#'pulmonary_artery', 
                        49: 67,#'rib_left_1', 
                        50: 85,#'rib_left_10', 
                        51: 87,#'rib_left_11',
                        52: 89,#'rib_left_12', 
                        53: 69,#'rib_left_2', 
                        54: 71,#'rib_left_3', 
                        55: 73,#'rib_left_4', 
                        56: 75,#'rib_left_5', 
                        57: 77,#'rib_left_6', 
                        58: 79,#'rib_left_7', 
                        59: 81,#'rib_left_8', 
                        60: 83,#'rib_left_9', 
                        61: 68,#'rib_right_1',
                        62: 86,#'rib_right_10',
                        63: 88,#'rib_right_11',
                        64: 90,#'rib_right_12', 
                        65: 70,#'rib_right_2', 
                        66: 72,#'rib_right_3', 
                        67: 74,#'rib_right_4', 
                        68: 76,#'rib_right_5', 
                        69: 78,#'rib_right_6', 
                        70: 80,#'rib_right_7', 
                        71: 82,#'rib_right_8', 
                        72: 84,#'rib_right_9',
                        73: 102,#'sacrum', 
                        74: 95,#'scapula_left', 
                        75: 96,#'scapula_right', 
                        76: 8,#'small_bowel',
                        77: 26,#'spleen', 
                        78: 7,#'stomach', 
                        79: 126,#'trachea',
                        80: None,#'urinary_bladder', 
                        81: 43,#'vertebrae_C1',
                        82: 44,#'vertebrae_C2', 
                        83: 45,#'vertebrae_C3', 
                        84: 46,#'vertebrae_C4', 
                        85: 47,#'vertebrae_C5', 
                        86: 48,#'vertebrae_C6', 
                        87: 49,#'vertebrae_C7', 
                        88: 62,#'vertebrae_L1', 
                        89: 63,#'vertebrae_L2', 
                        90: 64,#'vertebrae_L3', 
                        91: 65,#'vertebrae_L4', 
                        92: 66,#'vertebrae_L5', 
                        93: 50,#'vertebrae_T1', 
                        94: 59,#'vertebrae_T10',
                        95: 60,#'vertebrae_T11', 
                        96: 61,#'vertebrae_T12', 
                        97: 51,#'vertebrae_T2',
                        98: 52,#'vertebrae_T3',
                        99: 53,#'vertebrae_T4', 
                        100: 54,#'vertebrae_T5',
                        101: 55,#'vertebrae_T6', 
                        102: 56,#'vertebrae_T7', 
                        103: 57,#'vertebrae_T8', 
                        104:58,#'vertebrae_T9'
        }